# Lab 2: Vectors, Matrices and Systems of Linear Equations

In [1]:
row_vec = [1 3 5 7 9]

1×5 Matrix{Int64}:
 1  3  5  7  9

In [2]:
col_vec = [0; 2; 4; 6; 8]

5-element Vector{Int64}:
 0
 2
 4
 6
 8

In [3]:
A = [1 2 3 4; 5 6 7 8]

2×4 Matrix{Int64}:
 1  2  3  4
 5  6  7  8

### Practice 1.

In [4]:
almost_zero_vec = [0; 0; -1.5; 0; 0]

5-element Vector{Float64}:
  0.0
  0.0
 -1.5
  0.0
  0.0

In [5]:
zeor_matrix = zeros(3, 4)

3×4 Matrix{Float64}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

In [9]:
two_matrix = ones(3, 4) .+ 1
# pay attention to the . placed before +

3×4 Matrix{Float64}:
 2.0  2.0  2.0  2.0
 2.0  2.0  2.0  2.0
 2.0  2.0  2.0  2.0

In [27]:
using Random
Random.seed!(1234)
rand_matrix = rand(3, 4)

3×4 Matrix{Float64}:
 0.579862  0.0149088  0.839622  0.946453
 0.411294  0.520355   0.967143  0.574323
 0.972136  0.639562   0.131026  0.67765

### Example 2

In [60]:
row_vec = [1 3 5 7 9]
almost_zero_vec = [0; 0; -pi; 0; 0; 0; 0]
using Random    # using an external pacakge
Random.seed!(1234)
rand_matrix = rand(3, 4)

3×4 Matrix{Float64}:
 0.579862  0.0149088  0.839622  0.946453
 0.411294  0.520355   0.967143  0.574323
 0.972136  0.639562   0.131026  0.67765

In [61]:
num = row_vec[1]

1

In [62]:
num = almost_zero_vec[3]

-3.141592653589793

In [63]:
num = rand_matrix[1, 2]

0.014908849285099945

In [64]:
vect = rand_matrix[:, 4]

3-element Vector{Float64}:
 0.9464532262313834
 0.5743234852783174
 0.6776499075995779

In [66]:
vect = rand_matrix[1, :]

4-element Vector{Float64}:
 0.5798621201341324
 0.014908849285099945
 0.8396219340580711
 0.9464532262313834

In [67]:
vect = rand_matrix[1:1, 1:end]

1×4 Matrix{Float64}:
 0.579862  0.0149088  0.839622  0.946453

In [68]:
vect = rand_matrix[1:1, :]

1×4 Matrix{Float64}:
 0.579862  0.0149088  0.839622  0.946453

3-element Vector{Float64}:
 0.5798621201341324
 0.4112941179498505
 0.9721360824554687

In [71]:
A = [1 2 3 0; 4 5 6 0; 7 8 9 0; 0 0 0 0]

4×4 Matrix{Int64}:
 1  2  3  0
 4  5  6  0
 7  8  9  0
 0  0  0  0

In [72]:
block = A[1:3, 1:3]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [73]:
small_block = block[2:2, 2:2]

1×1 Matrix{Int64}:
 5

In [75]:
num = small_block[1]

5

In [76]:
pi / small_block

MethodError: MethodError: no method matching /(::Irrational{:π}, ::Matrix{Int64})
The function `/` exists, but no method is defined for this combination of argument types.

You might have used a 2d row vector where a 1d column vector was required.
Note the difference between 1d column vector [1,2,3] and 2d row vector [1 2 3].
You can convert to a column vector with the vec() function.

Closest candidates are:
  /(::Number, !Matched::BitArray)
   @ Base bitarray.jl:1205
  /(::Number, !Matched::AbstractVector)
   @ LinearAlgebra C:\Users\mabah\AppData\Local\Programs\Julia-1.11.2\share\julia\stdlib\v1.11\LinearAlgebra\src\generic.jl:1168
  /(::Number, !Matched::Missing)
   @ Base missing.jl:124
  ...


In [77]:
pi ./ small_block

1×1 Matrix{Float64}:
 0.6283185307179586

In [78]:
pi / small_block[1]

0.6283185307179586

In [79]:
col_vec

UndefVarError: UndefVarError: `col_vec` not defined in `Main`
Suggestion: check for spelling errors or missing imports.