# Lab 2: Vectors, Matrices and Systems of Linear Equations

In [1]:
row_vec = [1 3 5 7 9]

1×5 Matrix{Int64}:
 1  3  5  7  9

In [2]:
col_vec = [0; 2; 4; 6; 8]

5-element Vector{Int64}:
 0
 2
 4
 6
 8

In [3]:
A = [1 2 3 4; 5 6 7 8]

2×4 Matrix{Int64}:
 1  2  3  4
 5  6  7  8

### Practice 1.

In [4]:
almost_zero_vec = [0; 0; -1.5; 0; 0]

5-element Vector{Float64}:
  0.0
  0.0
 -1.5
  0.0
  0.0

In [5]:
zeor_matrix = zeros(3, 4)

3×4 Matrix{Float64}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

In [9]:
two_matrix = ones(3, 4) .+ 1
# pay attention to the . placed before +

3×4 Matrix{Float64}:
 2.0  2.0  2.0  2.0
 2.0  2.0  2.0  2.0
 2.0  2.0  2.0  2.0

In [24]:
using Random
Random.seed!(1234)
rand_matrix = rand(3, 4)

3×4 Matrix{Float64}:
 0.579862  0.0149088  0.839622  0.946453
 0.411294  0.520355   0.967143  0.574323
 0.972136  0.639562   0.131026  0.67765

In [4]:
2+2

4