# Lab 3: Vector and Matrix Multiplicatopn

In [2]:
ex1a = [1 2 3; 4 5 6; 7 8 9]
ex1b = [1 2 3 4 5; 6 7 8 9 10; 11 12 13 14 15]

size(ex1a * ex1b)

(3, 5)

In [3]:
size(ex1b * ex1a)

DimensionMismatch: DimensionMismatch: matrix A has axes (Base.OneTo(3),Base.OneTo(5)), matrix B has axes (Base.OneTo(3),Base.OneTo(3))

## Problem 1
### a)

In [14]:
source1 = collect(1:12)
source2 = collect(12:-1:1)
matrix1 = reshape(source1, 3, :)
matrix2 = reshape(source2, 4, :)
matProduct1a = matrix1 * matrix2

3×3 Matrix{Int64}:
 216  128  40
 258  154  50
 300  180  60

### c) Clever indexing  + resultant size

In [31]:
A = [1 2 3; 4 5 6]
B = [0 1 1 2; 3 5 8 13; 21 34 55 89]

C=A*B

topRow = C[1, :]
botRow = C[size(C, 1), :]   # or ----> botRow = C[end, :]
leftCol = C[:, 1]
rightCol = C[:, size(C, 2)] # or -.--> rightCol = C[:, end]

2-element Vector{Int64}:
 295
 607

## Problem 2
### a)

In [45]:
F = [4 3; 7 9]
G = [5; 6]

Fr1 = F[1:1, :]
Fr2 = F[2:2, :]

Gc1 = G[:, 1:1]

@show Fr1*Gc1
@show Fr2*Gc1

FG = [Fr1*Gc1; Fr2*Gc1]

Fr1 * Gc1 = [38;;]
Fr2 * Gc1 = [89;;]


2×1 Matrix{Int64}:
 38
 89

### b)

In [37]:
C = [2 4 6; 3 5 7]
D = [9 10; 13 14; 18 19]

CD = zeros(2, 2)

for i in 1:size(C, 1)
    for j in 1:size(D, 2)
        CD[i, j] = (C[i:i, :] * D[:, j:j])[1]
    end
end

CD

2×2 Matrix{Float64}:
 178.0  190.0
 218.0  233.0

In [41]:
C = [2 4 6; 3 5 7]
D = [9 10; 13 14; 18 19]

CD = zeros(2, 2)

for i in 1:size(C, 1)
    for j in 1:size(D, 2)
        for k in 1:size(C, 2)
            CD[i, j] += C[i, k] * D[k, j]
            @show CD
        end
    end
end

CD

CD = [18.0 0.0; 0.0 0.0]
CD = [70.0 0.0; 0.0 0.0]
CD = [178.0 0.0; 0.0 0.0]
CD = [178.0 20.0; 0.0 0.0]
CD = [178.0 76.0; 0.0 0.0]
CD = [178.0 190.0; 0.0 0.0]
CD = [178.0 190.0; 27.0 0.0]
CD = [178.0 190.0; 92.0 0.0]
CD = [178.0 190.0; 218.0 0.0]
CD = [178.0 190.0; 218.0 30.0]
CD = [178.0 190.0; 218.0 100.0]
CD = [178.0 190.0; 218.0 233.0]


2×2 Matrix{Float64}:
 178.0  190.0
 218.0  233.0

### C) Function

In [49]:
function matrix_multiply(A, B)
    rows = size(A, 1)
    cols = size(B, 2)
    CD = zeros(rows, cols)

    for i in 1:rows
        for j in 1:cols
            CD[i, j] = (C[i:i, :] * D[:, j:j])[1]
        end
    end
    return CD

end

    

matrix_multiply (generic function with 1 method)

In [51]:
using Random
C=rand(3,40)
D=randn(40,5)

C_D = C * D

func_ans = matrix_multiply(C,D)

diff = func_ans - C_D

3×5 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

### Problem 3. Matrix Reversal (just rows)

In [77]:
function matrixReverserRows(A)
    rows, cols = size(A)
    dummy = zeros(rows, cols)
    for i in 0:cols-1
        dummy[:, cols-i] = A[:, i+1]
    end
    return dummy
end


matrixReverserRows (generic function with 1 method)

In [80]:
C = [1 2 3; 4 5 6; 7 8 9]
matrixReverserRows(C)

3×3 Matrix{Float64}:
 3.0  2.0  1.0
 6.0  5.0  4.0
 9.0  8.0  7.0

### Problem 4. Matrix Reversal (rows and columns)

In [71]:
function matrixReverser(A)
    rows, cols = size(A)
    dummy = zeros(rows*cols)
    for i in 0:rows*cols-1
        dummy[i+1] = A[rows*cols-i]
    end
    print(dummy)
    return reshape(dummy, rows, cols)
end


matrixReverser (generic function with 1 method)

In [81]:
C = [1 2 3; 4 5 6; 7 8 9]
matrixReverser(C)

[9.0, 6.0, 3.0, 8.0, 5.0, 2.0, 7.0, 4.0, 1.0]

3×3 Matrix{Float64}:
 9.0  8.0  7.0
 6.0  5.0  4.0
 3.0  2.0  1.0