# Lab 3: Vector and Matrix Multiplicatopn

In [2]:
ex1a = [1 2 3; 4 5 6; 7 8 9]
ex1b = [1 2 3 4 5; 6 7 8 9 10; 11 12 13 14 15]

size(ex1a * ex1b)

(3, 5)

In [3]:
size(ex1b * ex1a)

DimensionMismatch: DimensionMismatch: matrix A has axes (Base.OneTo(3),Base.OneTo(5)), matrix B has axes (Base.OneTo(3),Base.OneTo(3))

## Problem 1
### a)

In [14]:
source1 = collect(1:12)
source2 = collect(12:-1:1)
matrix1 = reshape(source1, 3, :)
matrix2 = reshape(source2, 4, :)
matProduct1a = matrix1 * matrix2

3×3 Matrix{Int64}:
 216  128  40
 258  154  50
 300  180  60

### c) Clever indexing  + resultant size

In [31]:
A = [1 2 3; 4 5 6]
B = [0 1 1 2; 3 5 8 13; 21 34 55 89]

C=A*B

topRow = C[1, :]
botRow = C[size(C, 1), :]   # or ----> botRow = C[end, :]
leftCol = C[:, 1]
rightCol = C[:, size(C, 2)] # or -.--> rightCol = C[:, end]

2-element Vector{Int64}:
 295
 607

## Problem 2
### a)

In [35]:
F = [4 3; 7 9]
G = [5; 6]

Fr1 = F[1:1, :]
Fr2 = F[2:2, :]

Gc1 = G[:, 1:1]

2×1 Matrix{Int64}:
 5
 6

### b)

In [37]:
C = [2 4 6; 3 5 7]
D = [9 10; 13 14; 18 19]

CD = zeros(2, 2)

for i in 1:size(C, 1)
    for j in 1:size(D, 2)
        CD[i, j] = (C[i:i, :] * D[:, j:j])[1]
    end
end

CD

2×2 Matrix{Float64}:
 178.0  190.0
 218.0  233.0

In [40]:
C = [2 4 6; 3 5 7]
D = [9 10; 13 14; 18 19]

CD = zeros(2, 2)

for i in 1:size(C, 1)
    for j in 1:size(D, 2)
        for k in 1:size(C, 2)
            CD[i, j] += C[i, k] * D[k, j]
        end
    end
end

CD

2×2 Matrix{Float64}:
 178.0  190.0
 218.0  233.0